### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@strengejacke I noticed that currently in the readme the chunk of glmAdaptive is commented out. Any particular reason? I did so PRs by mistake and had to manually resolve conflicts... in the end I de-commented out the lines.

I have to merge this to update bayesindices.csv data (the script took about 10 days to run on the server), but feel free to re-comment and change the README as you want!

**Comment by DominiqueMakowski** [comment]
Alright I am not sure of my changes and fixes and hope that my update didn't overwrite any of your previous changes! Otherwise I will go in and retrieve them

**Comment by strengejacke** [comment]
I haven't touched the readme actually. I only added the data files and revised some docs (rd files).

**Comment by strengejacke** [comment]
Are you sure you handled the data objects correctly? The new .csv has no `noise`-variable, and [checks are failing now](https://cran.r-project.org/web/checks/check_results_bayestestR.html).

**Comment by DominiqueMakowski** [comment]
Yes sorry, this is expected, I am currently rewriting these 2 bayestestR vignettes...

**Pull request merged**
